Replaced digit-initial QNames (variable names) with the corresponding number as letter - QNames are not allowed to start with digits.
The old QNames didn't cause any bugs that I'm aware of, but at least we get rid of a couple of warnings:

compilation error: file /Users/sjur/langtech/main/gt/script/common.xsl line 734 element variable
The value '1Target' of the attribute 'name' is not a valid QName.
compilation error: file /Users/sjur/langtech/main/gt/script/common.xsl line 735 element variable
The value '1Replacement' of the attribute 'name' is not a valid QName.

The updated version gives no errors or warnings.